server:
  port: 9000
  
spring:
  application:
    name: msap-config-server
    
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/jukyellow/public-msap.git
          
management:
  endpoints:
    env:
      enabled: true
    web:
      exposure:
        include:*
