#Eureka Standalone Server       
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:${server.port}/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:*
